### ISSUE TITLE
Dependency on lodash.findindex causes deep file tree and long paths that breaks Windows

### ISSUE THREAD

**Issue by CaleyD** [yocontra/glob2base#4]
Would you accept a pull request to update the dependency to the full lodash module? 

It would help a lot of us Windows devs who would like to use this module (and other packages that depend on it, like gulp).

Here's a discussion of the issue - https://github.com/joyent/node/issues/6960. The custom lodash builds are particularly painful...

Cheers,
Caley

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages:

```
lodash.findindex@3.0.0
└─┬ lodash._basecallback@3.2.0
  ├─┬ lodash._baseisequal@3.0.1
  │ ├── lodash.isarray@3.0.0
  │ └── lodash.istypedarray@3.0.0
  ├── lodash._bindcallback@3.0.0
  └─┬ lodash.keys@3.0.3
    ├── lodash.isarguments@3.0.0
    ├── lodash.isarray@3.0.0
    └── lodash.isnative@3.0.0
```
